### ISSUE TITLE
Language agnostic bootstrapping mechanism

### ISSUE THREAD

**Issue by hadim** [hadim/scijava-jupyter-kernel#28]
As discussed in https://github.com/hadim/scijava-jupyter-kernel/issues/10#issuecomment-294511844 a language agnostic bootstrapping mechanism would allow to run a notebook file without the need of Fiji.

I think this need to be done in `scijava-common`.

**Comment by hadim** [comment]
I gonna start the implementation in this repo and move it to `scijava-common` when stable enough.

I'll start by stealing two groovy classes `groovy.grape.Grape` and `groovy.grape.GrapeEngine`, the hard is to implement `GrapeEngine`, I can probably reuse most the code of `groovy.grape.GrapeIvy` (groovy -> java conversion needed).

Note : here is the groovy code : https://github.com/apache/groovy/tree/master/src/main/groovy/grape

Now the thing I need to figure out is where in the `scijava-common`, `@Annotations` are parsed ? Because I'll have to hack this to execute a `Grape.grab("net.image:imagej-common:2.0.0")` method when needed.

**Comment by ctrueden** [comment]
> Now the thing I need to figure out is where in the `scijava-common`, `@Annotations` are parsed ? 

You mean where they are parsed for scripts? Or where are the `@Plugin` and `@Parameter` annotations handled for Java classes? Assuming you mean scripts, they are parsed by [this method](https://github.com/scijava/scijava-common/blob/scijava-common-2.62.1/src/main/java/org/scijava/script/ScriptInfo.java#L227-L306), which leans on [these methods](https://github.com/scijava/scijava-common/blob/scijava-common-2.62.1/src/main/java/org/scijava/script/ScriptInfo.java#L397-L439). Most of the hard work is done by Parsington, the SciJava expression parser. You could easily reuse that to handle anything inside the parentheses in a similar way.

**Comment by hadim** [comment]
See #37 for a first implementation.

@ctrueden I was looking at the code that parses the annotation in scripts. Thanks for the information, I should have enough to start with !

**Comment by hadim** [comment]
Some update here. Since #37 we have a working `GrapeService` that can download and cache any Maven artifacts + load them using a `ClassLoader`.

Check on this small notebook; the first import fails while the other one after grabbing the artifact works : https://gist.github.com/hadim/5fb72fc4ec9e92127d86e64922b881b3

**Comment by hadim** [comment]
https://github.com/scijava/scijava-common/pull/265 implements the needed code to do the magic.

And it seems to be working.

**Comment by ctrueden** [comment]
This is great!

One thing I'd like to discuss, since you needed to implement this feature yourself anyway: can we enrich it to show better progress relating to what's happening? The Beaker-based Grape support would simply hang until all dependency resolution was complete. And if something went wrong, there was little/no indication of what. There is as particular problematic artifact in the ImageJ2 dependency hierarchy—`asm-tree` IIRC?—which caused the bootstrapping to fail on many users' machines. They needed to manually copy this artifact from their `~/.m2/repository` into `~/.groovy/grapes`, and then rerun the notebook. It would of course be much nicer if the bootstrapping was more resilient and informative than that.

**Comment by hadim** [comment]
This mechanism is independent of this repo. See https://github.com/scijava/scijava-common/pull/265
