### ISSUE TITLE
ClassCastException when Displaying IntervalView

### ISSUE THREAD

**Issue by awalter17** [hadim/scijava-jupyter-kernel#55]
Hello!

I get a `java.lang.ClassCastException` when I try to execute the code below:
```
// @ImageJ ij
// @NotebookService nb

import net.imglib2.interpolation.randomaccess.NLinearInterpolatorFactory

clown = ij.io().open("http://imagej.net/images/clown.png")
scaleFactors = [0.5, 0.5, 1] 
interpolationStrategy = new NLinearInterpolatorFactory()
image = ij.op().run("scaleView", clown, scaleFactors, interpolationStrategy)
nb.display(image)
```
The exact error message is:
```
javax.script.ScriptException: java.lang.ClassCastException: net.imglib2.view.IntervalView cannot be cast to net.imglib2.img.Img
```

It seems to originate from the [RAIToPNGNotebookConverter](https://github.com/hadim/scijava-jupyter-kernel/blob/master/src/main/java/net/imagej/notebook/converter/RAIToPNGNotebookConverter.java#L49) class. Instead of casting the `object` to an `Img`, could you just cast it to a `RandomAccessibleInterval`?

Please feel free to let me know if you need any additional information from me.

**Comment by hadim** [comment]
You're right, we should cast to RAI. It's now done.

**Comment by hadim** [comment]
(and your code works with this commit)

You will have to compile the package yourself and move it to Fiji or your Conda installation to get this fix. I want to wait a bit before releasing a new version on conda-forge since your guys are testing the kernel at the moment.

The way I work when developing the kernel is to ask Maven to copy the jar to the Fiji directory. Then I don't use the conda package but from Fiji run `Analyze > Jupyter Kernel > Install Scijava Kernel` that will install the kernel linked to your Fiji installation. Then you just have to run install in Eclipse/Maven then restart the kernel (you don't have to restart Jupyter itself).

**Comment by ctrueden** [comment]
> You will have to compile the package yourself and move it to Fiji or your Conda installation to get this fix.

No problem, this is exactly what I do: symlink the `target/scijava-jupyter-kernel-0.3.3-SNAPSHOT.jar` into `~/anaconda3/envs/java_env/opt/scijava-jupyter-kernel/`, removing the stable `0.3.2` version first. Works great for testing.

> I want to wait a bit before releasing a new version on conda-forge since your guys are testing the kernel at the moment.

Definitely; I have a bunch of fixes and cleanups I'm going to throw your way soon. :-)
